services:
  portal:
    image: image-portal-test
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-portal-test
    restart: unless-stopped
    ports:
      - "127.0.0.1:8091:80"
    networks:
      - network-portal-test

networks:
  network-portal-test:
    driver: bridge
