services:
  portal:
    image: image-portal-prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-portal-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8089:80"
    networks:
      - network-portal-prod

networks:
  network-portal-prod:
    driver: bridge
