services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hasten-portal-test
    restart: unless-stopped
    ports:
      - "127.0.0.1:8091:80"
    networks:
      - hasten-portal-test-net

networks:
  hasten-portal-test-net:
    driver: bridge
